name: kioju_link_manager
description: Cross-platform Flutter app to manage Kioju links and bookmarks
publish_to: "none"
version: 2.2.0

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  provider: ^6.1.5+1
  html: ^0.15.6
  url_launcher: ^6.3.2
  file_selector: ^1.0.3
  shared_preferences: ^2.5.3
  package_info_plus: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  msix: ^3.16.7
  flutter_distributor: ^0.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/kioju-icon.png

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: false # Set to true if you add Android support later
  ios: false # Set to true if you add iOS support later
  windows:
    generate: true
    image_path: "assets/kioju-icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/kioju-icon.png"

# MSIX configuration for Windows installer
msix_config:
  display_name: Kioju Link Manager
  publisher_display_name: SilverDay
  identity_name: com.silverday.kiojulinkmanager
  msix_version: 2.0.0.0
  logo_path: assets\kioju-icon.png
  capabilities: internetClient
  description: Cross-platform Flutter app to manage Kioju links and bookmarks
  publisher: CN=SilverDay
  languages: en-us
